# Generated by Django 4.0.5 on 2022-06-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('vehicle_number', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False)),
                ('vehicle_model', models.CharField(max_length=200, null=True)),
                ('vehicle_type', models.CharField(choices=[('Two wheeler', 'Two wheeler'), ('Two wheeler', 'Three wheeler'), ('Two wheeler', 'Four wheeler')], max_length=100, null=True)),
                ('vehicle_description', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'vehicle_col',
            },
        ),
    ]
